version: '3.8'


networks:
  red_mern:

services:
  baseDatos:
    container_name: baseDatos
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    networks:
      - red_mern

  mern-backend:
    container_name: mern-backend
    image: image-mern-backend:latest
    ports:
      - "3006:3006" 
    restart: always
    networks:
      - red_mern
    depends_on:
      - baseDatos
  
  mern-frontend:
    container_name: mern-frontend
    image: image-mern-frontend:latest
    ports:
      - "3000:3000" 
    restart: always
    networks:
      - red_mern
    depends_on:
      - mern-backend
